default: &default
  adapter: postgresql
  encoding: unicode
  host: db1
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: active_storage_demo_development


test:
  <<: *default
  database: active_storage_demo_test
